// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  return `[![License:${license}](https://img.shields.io/badge/license-${renderLicenseSection(
    license
  )})](${renderLicenseLink(license)})<br />`;
}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {
  switch (license) {
    case "Apache":
      return "https://opensource.org/licenses/Apache-2.0";

    case "GNU":
      return "https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html";

    case "IBM":
      return "https://opensource.org/licenses/IPL-1.0";

    case "ISC":
      return "https://opensource.org/licenses/MPL-2.0";

    case "MIT":
      return "https://opensource.org/licenses/MIT";

    case "Mozilla":
      return "https://opensource.org/licenses/MPL-2.0";

    case "Open":
      return "https://opendatacommons.org/licenses/by/";

    default:
      return "";
  }
}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {
  switch (license) {
    case "Apache":
      return "Apache%202.0-blue.svg";

    case "GNU":
      return "GPL%20v2-blue.svg";

    case "IBM":
      return "IPL%201.0-blue.svg";

    case "ISC":
      return "MPL%202.0-brightgreen.svg";

    case "MIT":
      return "MIT-yellow.svg";

    case "Mozilla":
      return "MPL%202.0-brightgreen.svg";

    case "Open":
      return "ODC_BY-brightgreen.svg";

    default:
      return "";
  }
}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `# ${data.title}


 ${renderLicenseBadge(data.license)}

 <br />
 
 
 ## Description
 ${data.description}
 
 ## Table of Contents
 * [Installation](#installation)
 * [Usage](#usage)
 * [License](#license)
 * [Testss](#Tests)
 * [Contributions](#Contribution)
 * [Questionss](#Questions)
 
             
 ## installation
 ${data.installation}
     
         
 ## Usage
 ${data.usage}
 
 ## License
 

 This application is covered by the ${renderLicenseSection(
   data.license
 )} license. 
 
 ## Contribution
 ${data.Contribution}
 
 ## Tests
 ${data.Tests}
 
 ## Questions
 For any questions, please contact me with the information below:
 
 Find me on Github: 
 [${data.username}](https://github.com/${data.username})<br />
 Email me with any questions: Email[${data.email}]<br />
 This README was generated by [READme generator](https://github.com/akash2040/Generate_Readme)
 
 `;
}

module.exports = generateMarkdown;
